version: '3.4'

services:
  WebApiRestUdemy:
    image: ${DOCKER_REGISTRY-}apimysqldocker
    container_name: restudemy.api
    build:
      context: .
      dockerfile: WebApiRestUdemy/Dockerfile
    depends_on:
    - database
    ports:
    - "5000:80"
    restart: always
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql
    container_name: mysqldb
    ports:
     - "3306:3306" 
    expose:
     - 3306
    volumes:
     - dbmysql-volume:/var/lib/mysql
    restart: always
    environment:
     MYSQL_RANDOM_ROOT_PASSWORD: 1
     MYSQL_PASSWORD: root
     MYSQL_DATABASE: rest_api_net_udemy

volumes:
  dbmysql-volume:   